name: update

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write  # ← 여기가 핵심입니다!

jobs:
  update-readme:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-leetcode

    - name: Run update.py
      run: |
        python update.py

    - name: Check if README.md changed
      run: |
        git diff --exit-code
      continue-on-error: true

    - name: Commit changes
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git add -A
        git commit -am "auto update README.md" || echo "No changes to commit"

    - name: Set up authentication
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

    - name: Push changes
      run: git push
